FORMATIONS = {
    "4-3-3": [4, 3, 3],
    "4-4-2": [4, 4, 2],
    "4-2-3-1": [4, 2, 3, 1],
    "3-5-2": [3, 5, 2],
    "5-3-2": [5, 3, 2],
}

SAMPLE_FRAME_COUNT = 10
EXPECTED_OUTFIELD_PLAYERS = 10
MIN_TRACK_OBSERVATIONS = 2
DEFAULT_TRACK_FRAME_STRIDE = 5

TEAM_ABBREVIATIONS = {
    "ARS": "Arsenal",
    "AVL": "Aston Villa",
    "BOU": "Bournemouth",
    "BRE": "Brentford",
    "BHA": "Brighton & Hove Albion",
    "BRI": "Brighton & Hove Albion",
    "BUR": "Burnley",
    "CHE": "Chelsea",
    "CRY": "Crystal Palace",
    "EVE": "Everton",
    "FUL": "Fulham",
    "IPS": "Ipswich Town",
    "LEE": "Leeds United",
    "LEI": "Leicester City",
    "LIV": "Liverpool",
    "LUT": "Luton Town",
    "MCI": "Manchester City",
    "MUN": "Manchester United",
    "NEW": "Newcastle United",
    "NFO": "Nottingham Forest",
    "NOT": "Nottingham Forest",
    "SHU": "Sheffield United",
    "SOU": "Southampton",
    "SUN": "Sunderland",
    "TOT": "Tottenham Hotspur",
    "WBA": "West Bromwich Albion",
    "WHU": "West Ham United",
    "WOL": "Wolverhampton Wanderers",
    "ALA": "Alaves",
    "ATH": "Athletic Club",
    "ATM": "Atletico Madrid",
    "ATL": "Atletico Madrid",
    "BAR": "Barcelona",
    "BET": "Real Betis",
    "CAD": "Cadiz",
    "CEL": "Celta Vigo",
    "ELC": "Elche",
    "ESP": "Espanyol",
    "FCB": "Barcelona",
    "GET": "Getafe",
    "GIR": "Girona",
    "GRA": "Granada",
    "LPA": "Las Palmas",
    "LAS": "Las Palmas",
    "LEG": "Leganes",
    "MLL": "Mallorca",
    "OSA": "Osasuna",
    "RAY": "Rayo Vallecano",
    "RMA": "Real Madrid",
    "RMD": "Real Madrid",
    "RSO": "Real Sociedad",
    "SEV": "Sevilla",
    "VAL": "Valencia",
    "VIL": "Villarreal",
    "VLL": "Real Valladolid",
}

TEAM_NAME_ALIASES = {
    "arsenal": "Arsenal",
    "aston villa": "Aston Villa",
    "bournemouth": "Bournemouth",
    "brentford": "Brentford",
    "brighton": "Brighton & Hove Albion",
    "burnley": "Burnley",
    "chelsea": "Chelsea",
    "crystal palace": "Crystal Palace",
    "everton": "Everton",
    "fulham": "Fulham",
    "ipswich": "Ipswich Town",
    "leeds": "Leeds United",
    "leeds united": "Leeds United",
    "leicester": "Leicester City",
    "liverpool": "Liverpool",
    "manchester city": "Manchester City",
    "man city": "Manchester City",
    "manchester united": "Manchester United",
    "man united": "Manchester United",
    "newcastle": "Newcastle United",
    "nottingham forest": "Nottingham Forest",
    "southampton": "Southampton",
    "sunderland": "Sunderland",
    "tottenham": "Tottenham Hotspur",
    "tottenham hotspur": "Tottenham Hotspur",
    "west ham": "West Ham United",
    "wolves": "Wolverhampton Wanderers",
    "wolverhampton": "Wolverhampton Wanderers",
    "athletic club": "Athletic Club",
    "atletico madrid": "Atletico Madrid",
    "barcelona": "Barcelona",
    "real madrid": "Real Madrid",
    "real sociedad": "Real Sociedad",
    "sevilla": "Sevilla",
    "valencia": "Valencia",
    "villarreal": "Villarreal",
}
